using Oscar
using Pkg.MiniProgressBars

function cantor_pairs(A, B)
    n = length(A)
    m = length(B)

    result = []

    for s in 2:(n + m)  # s = i + j
        for i in max(1, s - m):min(n, s - 1)
            j = s - i
            push!(result, (A[i], B[j]))
        end
    end

    return result
end


function p_class_group_prime_basis(K::NumField, p::Int)

    @assert is_prime(ZZ(p)) "p must be prime"

    O = maximal_order(K)

    # Class group
    Cl, mCl = class_group(O)

    # Quotient A = Cl/pCl
    A, π = quo(Cl, p)

    # If trivial, return empty list
    if order(A) == 1
        return AbsSimpleNumFieldOrderIdeal[]
    end

    # GRH factor base bound
    B = Hecke.factor_base_bound_grh(O)

    # Prime ideals generating Cl(K)
    L = Hecke.prime_ideals_up_to(O, B)

    T = AbsSimpleNumFieldOrderIdeal[]

    # Current quotient map Cl -> A
    current_map = π
    current_group = A

    for q in L

        # class of q in current quotient
        c = current_map(mCl\q)

        # skip trivial classes
        if isone(c)
            continue
        end

        # keep q
        push!(T, q)

        # quotient out by subgroup generated by c
        current_group, ψ = quo(current_group, sub(current_group, [c])[1])

        # update map Cl -> current_group
        current_map =  current_map * ψ 

        # stop once quotient becomes trivial
        if order(current_group) == 1
            break
        end
    end

    return T
end

function increasing_combinations(A::Vector{Int}, k::Int)
    return [collect(c) for c in combinations(sort(A), k)]
end

function koch_tuple(K::AbsSimpleNumField,p::Int;bound::Int=10^3)
    T=p_class_group_prime_basis(K, p)
    OK=maximal_order(K)
    dk=signature(K)[1]+signature(K)[2]-1+length(T)
    tame_ideals=filter(q-> norm(q) % p == 1 && !(q in T), Hecke.prime_ideals_up_to(OK, bound))
    for a in increasing_combinations(collect(1:length(tame_ideals)),dk)
        m=1*OK
        for i in a
            m=m*tame_ideals[i]
        end
        if order(ray_class_group(m;n_quo=p)[1])==p^length(T)
            S=[tame_ideals[i] for i in a]
            return (S,T)
        end
    end
    return (AbsSimpleNumFieldOrderIdeal[],T)
end

using Oscar
using Hecke


# =============================================================================
# precompute fields attached to S
# =============================================================================

function precompute_linking_data(
    K::AbsSimpleNumField,
    p::Int,
    S::Vector{AbsSimpleNumFieldOrderIdeal},
    SS::Vector{AbsSimpleNumFieldOrderIdeal},
    T::Vector{AbsSimpleNumFieldOrderIdeal}
    )

    O = maximal_order(K)

    mm = prod(SS; init = one(O))

    cyclic_extensions = Dict{
        AbsSimpleNumFieldOrderIdeal,
        ClassField
    }()

    frob_maps = Dict{
        AbsSimpleNumFieldOrderIdeal,
        Any
    }()

    aut_groups = Dict{
        AbsSimpleNumFieldOrderIdeal,
        Any
    }()

    for q in S

        println("precomputing extension for ", q)

        ClS, ClS_map = ray_class_group(mm*q; n_quo = p)

        T_subgroup = sub(ClS, FinGenAbGroupElem[ClS_map \ t for t in T])[1]

        _, quo_map = quo(ClS, T_subgroup)

        Kq = ray_class_field(ClS_map, quo_map)

        cyclic_extensions[q] = Kq
    end

    return (
        cyclic_extensions = cyclic_extensions,
        modulus = mm
    )
end



# =============================================================================
# main search function
# =============================================================================

function find_mild_extension(
    K::AbsSimpleNumField,
    p::Int,
    S::Vector{AbsSimpleNumFieldOrderIdeal},
    SS::Vector{AbsSimpleNumFieldOrderIdeal},
    T::Vector{AbsSimpleNumFieldOrderIdeal};
    bound::Int = 10^3
    )

    d = length(S)
    dd = length(SS)

    O = maximal_order(K)

    # -------------------------------------------------------------------------
    # precompute all fields attached to S
    # -------------------------------------------------------------------------

    S_data = precompute_linking_data(K, p, S, SS, T)

    excluded = Set(vcat(S, SS, T))
    primes = filter(
        q -> mod(norm(q), p) == 1 && !(q in excluded),
        prime_ideals_up_to(O, bound)
    )

    # -------------------------------------------------------------------------
    # main loop over candidate primes a
    # -------------------------------------------------------------------------
    
    bar = MiniProgressBar(
        header = "Going through candidate prime a1",
        color = Base.info_color(),
        width = 40,
    )
    bar.max=length(primes)

    a1=1*O


    for j in 1:length(primes)
        a=primes[j]
        bar.current=j
        show_progress(stdout, bar)

        # =====================================================================
        # test conditions involving l(a,q)
        # =====================================================================

        possible_a1 = true

        for i in 1:d-1
            if prime_decomposition_type(S_data.cyclic_extensions[S[i]], a)[2] != 1
                possible_a1 = false
            end
        end
        possible_a1 =
            possible_a1 &&
            (prime_decomposition_type(S_data.cyclic_extensions[S[d]], a)[2] != 1)

        # if neither survives, skip expensive field construction
        if !(possible_a1)
            continue
        end

        # =====================================================================
        # ONLY NOW construct K_a
        # =====================================================================
        ClA, ClA_map = ray_class_group(S_data.modulus*a; n_quo = p)
        T_subgroup = sub(ClA, FinGenAbGroupElem[ClA_map \ t for t in T])[1]
        _, quo_map = quo(ClA, T_subgroup)
        Ka = ray_class_field(ClA_map, quo_map)

        # =====================================================================
        # finalize a1 test
        # =====================================================================
        

        for q in SS
            if possible_a1
                if prime_decomposition_type(Ka, q)[3] != p 
                    possible_a1 = false
                end
            end
        end
        
        for i in 1:d-1
            if possible_a1
                if prime_decomposition_type(Ka, S[i])[2] != p
                    possible_a1 = false
                    break
                end
            end
        end

        possible_a1 =
            possible_a1 &&
            (prime_decomposition_type(Ka, S[d])[3] == p)

        if possible_a1
            a1=a
            break
        end
    end

    ClA, ClA_map = ray_class_group(S_data.modulus*a1; n_quo = p)
    T_subgroup = sub(ClA, FinGenAbGroupElem[ClA_map \ t for t in T])[1]
    _, quo_map = quo(ClA, T_subgroup)
    Ka1 = ray_class_field(ClA_map, quo_map)
    S_data.cyclic_extensions[a1] = Ka1

    # =====================================================================
    # Search for a2, now that a1 is fixed
    # =====================================================================

    bar = MiniProgressBar(
        header = "Going through candidate primes a2",
        color = Base.info_color(),
        width = 40,
    )
    bar.max=length(primes)

    a2=1*O

    for j in 1:length(primes)
        a=primes[j]
        bar.current=j
        show_progress(stdout, bar)

        possible_a2 = true

        for i in 1:d-1
            if prime_decomposition_type(S_data.cyclic_extensions[S[i+1]], a)[3] == 1
                possible_a2 = false
            end
        end
        possible_a2 =
            possible_a2 &&
            (prime_decomposition_type(S_data.cyclic_extensions[S[1]], a)[2] != 1) &&
            (prime_decomposition_type(Ka1, a)[3] == p)

        # if neither survives, skip expensive field construction
        if !possible_a2
            continue
        end

        # =====================================================================
        # ONLY NOW construct K_a
        # =====================================================================
        ClA, ClA_map = ray_class_group(S_data.modulus*a; n_quo = p)
        T_subgroup = sub(ClA, FinGenAbGroupElem[ClA_map \ t for t in T])[1]
        _, quo_map = quo(ClA, T_subgroup)
        Ka = ray_class_field(ClA_map, quo_map)
        


        for q in SS
            if possible_a2
                if prime_decomposition_type(Ka, q)[1] != p 
                    possible_a2 = false
                end
            end
        end
        
        for i in 1:d-1
            if possible_a2
                if prime_decomposition_type(Ka, S[i])[3] != p
                    possible_a2 = false
                    break
                end
            end
        end

        possible_a2 =
            possible_a2 &&
            (prime_decomposition_type(Ka, S[d])[2] == p) &&
            (prime_decomposition_type(Ka, a1)[3] == p)

        if possible_a2
            a2=a
            break
        end
    end
    ClA, ClA_map = ray_class_group(S_data.modulus*a2; n_quo = p)
    T_subgroup = sub(ClA, FinGenAbGroupElem[ClA_map \ t for t in T])[1]
    _, quo_map = quo(ClA, T_subgroup)
    Ka2 = ray_class_field(ClA_map, quo_map)
    S_data.cyclic_extensions[a2] = Ka2

    b=AbsSimpleNumFieldOrderIdeal[]
    for j in 1:dd
        bar = MiniProgressBar(
        header = "Going through candidate primes b$(j)",
        color = Base.info_color(),
        width = 40,
        )
        bar.max=length(primes)

        for k in 1:length(primes)
            bar.current=k
            show_progress(stdout, bar)
            b_cand=primes[k]
            possible_b_cand=prime_decomposition_type(Ka1, b_cand)[2] == p
            for q in union(collect(keys(S_data.cyclic_extensions)),b)
                if q == a1 
                    continue
                end
                possible_b_cand=possible_b_cand && prime_decomposition_type(S_data.cyclic_extensions[q], b_cand)[3] == p
            end
            if !possible_b_cand
                continue
            end
            ClB, ClB_map = ray_class_group(S_data.modulus*b_cand; n_quo = p)
            T_subgroup = sub(ClB, FinGenAbGroupElem[ClB_map \ t for t in T])[1]
            _, quo_map = quo(ClB, T_subgroup)
            Kb = ray_class_field(ClB_map, quo_map)
            possible_b_cand=possible_b_cand && prime_decomposition_type(Kb, SS[j])[2] == p
            for q in union(collect(keys(S_data.cyclic_extensions)),SS)
                if q == SS[j]
                    continue
                end
                possible_b_cand=possible_b_cand && prime_decomposition_type(Kb, q)[3] == p
            end
            if possible_b_cand
                push!(b,b_cand)
                S_data.cyclic_extensions[b_cand] = Kb
                break
            end
        end
    end
    return (a1, a2, b)

end